### ISSUE TITLE
Remove barriers to contributing part deux

### ISSUE THREAD

**Issue by olliewright** [barnardos/design-system#130] opened 2018-04-24 13:19 UTC
Rich:

Six point criteria:
https://github.com/barnardos/design-system/community

Contributing guidelines
https://help.github.com/articles/setting-guidelines-for-repository-contributors/

For the repository owner, contribution guidelines are a way to communicate how people should contribute.
For contributors, the guidelines help them verify that they're submitting well-formed pull requests and opening useful issues.

Adding code of conduct:
https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

A code of conduct (1) defines standards for how to engage in a community. (2) It signals an inclusive environment that respects all contributions. (3) It also outlines procedures for addressing problems between members of your project's community.

Do we take the same approach as writing content for the design system itself i.e. begin by writing the smallest amount of copy to address these user needs?

**Comment by jeddy3** [comment] 2018-04-25 08:58
Closing as dupe of https://github.com/barnardos/design-system/issues/38

**Closed by jeddy3** 2018-04-25 08:58 UTC
